### ISSUE TITLE
Don't Block Tokio Runtime in GC Thread

### ISSUE THREAD

**Issue by agavra** [slatedb/slatedb#380]
We should be using `tokio::select!` in the GC thread since `crossbeam_channel::select!` is synchronous so this would block the tokio runtime thread.

There may be some other changes required to make sure we don't block the tokio runtime

_Originally posted by @rodesai in https://github.com/slatedb/slatedb/pull/367#discussion_r1872214282_

**Comment by TwistingTwists** [comment]
To use `tokio::select!` which is async with `crossbeam::channel::tick`, there is special method `spawn_blocking` which spawns a new thread, puts the task on that and then continues. 

Here is a short example 

```rust
  // Create a ticker that ticks every 500ms
    let ticker = crossbeam_channel::tick(Duration::from_millis(500));
    
    // Convert crossbeam receiver to tokio's async receiver using a spawn_blocking
    let ticker_task = tokio::task::spawn_blocking(move || {
        ticker.recv().unwrap()
    });

```

and then we can use `ticker_task` which is a tokio::task on a brand new thread - inside `tokio::select!`

**Comment by TwistingTwists** [comment]
Can you please assign this to me @criccomini ?

**Comment by rodesai** [comment]
Assigned to you @TwistingTwists! You could also just use tokio's interval (https://docs.rs/tokio/latest/tokio/time/fn.interval.html), which should be simpler since it doesn't require spawning another blocking task.

**Comment by TwistingTwists** [comment]
@rodesai : Since the other tickers (https://github.com/slatedb/slatedb/blob/68f2599a8d97cc50591e3859123e0fdb9226cee9/src/garbage_collector.rs#L477-L481) use `crossbeam_channel`,  should they be moved  to use `tokio::Receiver` too?

Do we want to move away from `crossbeam_channel` for Gc Implementation?


if we move away from `crossbeam_channel::tick`, the closest implementation in tokio could be (with help of chatGPT)

```
use tokio::sync::mpsc;
use tokio::time::{Instant, interval};

#[derive(Debug)]
enum DirGcStatus {
    Indefinite(std::time::Duration),
    OneMore,
    Done,
}

impl DirGcStatus {
    pub async fn ticker(&self) -> mpsc::Receiver<Instant> {
        let (tx, rx) = mpsc::channel(32); // Create a new Tokio mpsc channel

        match self {
            DirGcStatus::Indefinite(duration) => {
                let tx = tx.clone();
                tokio::spawn(async move {
                    let mut interval = interval(*duration);
                    loop {
                        interval.tick().await;
                        let now = Instant::now();
                        if tx.send(now).await.is_err() {
                            break; // If sending fails, exit the loop
                        }
                    }
                });
            }
            DirGcStatus::OneMore => {
                let tx = tx.clone();
                tokio::spawn(async move {
                    let now = Instant::now();
                    if tx.send(now).await.is_err() {
                        return; // If sending fails, just return
                    }
                });
            }
            DirGcStatus::Done => {
                // No action needed; receiver will just remain idle
            }
        }

        rx
    }
}

```

**Comment by criccomini** [comment]
@TwistingTwists Ya, let's use tokio for everything in this file. Here's an alternative implementation (courtesy of Windsurf) for interval ticks:

```
diff --git a/src/garbage_collector.rs b/src/garbage_collector.rs
index 82e57a7..7be22a9 100644
--- a/src/garbage_collector.rs
+++ b/src/garbage_collector.rs
@@ -15,7 +15,9 @@ use std::sync::Arc;
 use std::time::{Duration, Instant};
 use std::{fmt, thread};
 use tokio::runtime::Handle;
+use tokio::sync::mpsc;
 use tokio::sync::watch;
+use tokio::time::Interval;
 use tracing::{debug, error, info};
 
 const DEFAULT_MIN_AGE: Duration = Duration::from_secs(86400);
@@ -26,7 +28,7 @@ enum GarbageCollectorMessage {
 }
 
 pub(crate) struct GarbageCollector {
-    main_tx: Arc<crossbeam_channel::Sender<GarbageCollectorMessage>>,
+    main_tx: Arc<mpsc::Sender<GarbageCollectorMessage>>,
     shutdown_rx: watch::Receiver<bool>,
 }
 
@@ -50,7 +52,7 @@ impl GarbageCollector {
         tokio_handle: Handle,
         db_stats: Arc<DbStats>,
     ) -> Self {
-        let (external_tx, external_rx) = crossbeam_channel::unbounded();
+        let (external_tx, external_rx) = mpsc::channel(100);
         let tokio_handle = options.gc_runtime.clone().unwrap_or(tokio_handle);
         let (shutdown_tx, shutdown_rx) = watch::channel(false);
 
@@ -97,13 +99,13 @@ impl GarbageCollector {
                 .expect("Failed to install CTRL+C signal handler");
             debug!("Intercepted SIGINT ... shutting down garbage collector");
             // if we cant send a shutdown message it's probably because it's already closed
-            let _ignored_error = main_tx.send(Shutdown);
+            let _ignored_error = main_tx.try_send(Shutdown);
         });
     }
 
     /// Triggers the main garbage collection thread to terminate
     fn trigger_shutdown(&self) {
-        if self.main_tx.send(Shutdown).is_err() {
+        if self.main_tx.try_send(Shutdown).is_err() {
             error!("Could not send shutdown signal to threads blocked on await_shutdown");
         }
     }
@@ -125,14 +127,14 @@ struct GarbageCollectorOrchestrator {
     manifest_store: Arc<ManifestStore>,
     table_store: Arc<TableStore>,
     options: GarbageCollectorOptions,
-    external_rx: crossbeam_channel::Receiver<GarbageCollectorMessage>,
+    external_rx: mpsc::Receiver<GarbageCollectorMessage>,
     db_stats: Arc<DbStats>,
 }
 
 trait GcTask {
     async fn collect(&self, utc_now: DateTime<Utc>) -> Result<(), SlateDBError>;
     fn status(&mut self) -> &mut DirGcStatus;
-    fn ticker(&self) -> crossbeam_channel::Receiver<Instant>;
+    fn ticker(&self) -> Interval;
     fn resource(&self) -> &str;
 }
 
@@ -214,7 +216,7 @@ impl GcTask for ManifestGcTask {
         &mut self.status
     }
 
-    fn ticker(&self) -> crossbeam_channel::Receiver<Instant> {
+    fn ticker(&self) -> Interval {
         self.status.ticker()
     }
 
@@ -317,7 +319,7 @@ impl GcTask for WalGcTask {
         &mut self.status
     }
 
-    fn ticker(&self) -> crossbeam_channel::Receiver<Instant> {
+    fn ticker(&self) -> Interval {
         self.status.ticker()
     }
 
@@ -408,7 +410,7 @@ impl GcTask for CompactedGcTask {
         &mut self.status
     }
 
-    fn ticker(&self) -> crossbeam_channel::Receiver<Instant> {
+    fn ticker(&self) -> Interval {
         self.status.ticker()
     }
 
@@ -455,7 +457,7 @@ impl GarbageCollectorOrchestrator {
 
     /// Run the garbage collector
     pub async fn run(&self) {
-        let log_ticker = crossbeam_channel::tick(Duration::from_secs(60));
+        let mut log_ticker = tokio::time::interval(Duration::from_secs(60));
 
         let mut wal_gc_task = WalGcTask::new(
             self.manifest_store.clone(),
@@ -475,9 +477,9 @@ impl GarbageCollectorOrchestrator {
             self.options.manifest_options,
         );
 
-        let manifest_ticker = manifest_gc_task.ticker();
-        let wal_ticker = wal_gc_task.ticker();
-        let compacted_ticker = compacted_gc_task.ticker();
+        let mut manifest_ticker = manifest_gc_task.ticker();
+        let mut wal_ticker = wal_gc_task.ticker();
+        let mut compacted_ticker = compacted_gc_task.ticker();
 
         info!(
             "Starting Garbage Collector with [manifest: {}], [wal: {}], [compacted: {}]",
@@ -487,25 +489,25 @@ impl GarbageCollectorOrchestrator {
         );
 
         loop {
-            crossbeam_channel::select! {
-                recv(log_ticker) -> _ => {
+            tokio::select! {
+                _ = log_ticker.tick() => {
                    debug!("GC has collected {} Manifests, {} WAL SSTs and {} Compacted SSTs.",
                         self.db_stats.gc_manifest_count.value.load(Ordering::SeqCst),
                         self.db_stats.gc_wal_count.value.load(Ordering::SeqCst),
                         self.db_stats.gc_compacted_count.value.load(Ordering::SeqCst)
                     );
                 },
-                recv(manifest_ticker) -> _ => { self.run_gc_task(&mut manifest_gc_task).await; },
-                recv(wal_ticker) -> _ => { self.run_gc_task(&mut wal_gc_task).await; },
-                recv(compacted_ticker) -> _ => { self.run_gc_task(&mut compacted_gc_task).await; },
-                recv(self.external_rx) -> msg => {
+                _ = manifest_ticker.tick() => { self.run_gc_task(&mut manifest_gc_task).await; },
+                _ = wal_ticker.tick() => { self.run_gc_task(&mut wal_gc_task).await; },
+                _ = compacted_ticker.tick() => { self.run_gc_task(&mut compacted_gc_task).await; },
+                msg = self.external_rx.recv() => {
                     match msg {
-                        Ok(Shutdown) => {
+                        Some(Shutdown) => {
                             info!("Garbage collector received shutdown signal... shutting down");
                             break
                         }
-                        Err(e) => {
-                            error!("Garbage collector received error message {}. Shutting down", e);
+                        None => {
+                            error!("Garbage collector channel closed. Shutting down");
                             break;
                         }
                     }
@@ -565,11 +567,11 @@ impl DirGcStatus {
         self == &DirGcStatus::Done
     }
 
-    fn ticker(&self) -> crossbeam_channel::Receiver<Instant> {
+    fn ticker(&self) -> Interval {
         match self {
-            DirGcStatus::Indefinite(duration) => crossbeam_channel::tick(*duration),
-            DirGcStatus::OneMore => crossbeam_channel::at(Instant::now()),
-            DirGcStatus::Done => crossbeam_channel::never(),
+            DirGcStatus::Indefinite(duration) => tokio::time::interval(*duration),
+            DirGcStatus::OneMore => tokio::time::interval_at(tokio::time::Instant::now(), Duration::from_secs(0)),
+            DirGcStatus::Done => tokio::time::interval(Duration::from_secs(u64::MAX)),
         }
     }
 
```

This looks more or less right, and is a bit cleaner than the approach you outlined.

**Comment by TwistingTwists** [comment]
Alright. Let's go for tokio then.  Will raise a PR soon.

**Comment by criccomini** [comment]
(Note: I applied the Windsurf patch and it causes the tests to hang. There's likely some changes that need to be done in the test code to make it work properly...)

**Comment by TwistingTwists** [comment]
Yup. Ran this. 

There appears to be a deadlock somewhere. 
```
[INFO  slatedb::garbage_collector::tests] Waiting for garbage collector to run

```
...bazzilion times

this is what the logs show in test environment.

**Comment by TwistingTwists** [comment]
> Yup. Ran this.
> 
> There appears to be a deadlock somewhere.
> 
> ```
> [INFO  slatedb::garbage_collector::tests] Waiting for garbage collector to run
> ```
> 
> ...bazzilion times
> 
> this is what the logs show in test environment.

when running the test multiple times, it panics sometimes.

```
> cargo test test_collect_garbage_compacted_ssts -- --nocapture

warning: `slatedb` (lib test) generated 1 warning (run `cargo fix --lib -p slatedb --tests` to apply 1 suggestion)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.16s
     Running unittests src/lib.rs (target/debug/deps/slatedb-16e126f635b0829d)

running 2 tests
thread 'slatedb-gc' panicked at src/garbage_collector.rs:608:17:
`period` must be non-zero.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'slatedb-gc' panicked at src/garbage_collector.rs:608:17:
`period` must be non-zero.

```

**Comment by TwistingTwists** [comment]
https://docs.rs/tokio/latest/tokio/time/fn.interval_at.html#panics

Panic was caused by this.

**Comment by criccomini** [comment]
SGTM. LMK if you need any help. Feel free to submit a draft PR.
